### ISSUE TITLE
Problem with accessing some tags in RSS Feeds

### ISSUE THREAD

**Issue by sahildave** [SamDecrock/node-xmlreader#5]
The RSS file that I am dealing with have this structure:

```
<rss>
|     <channel>
|     |     <title>some_heading</title>
|     |     <image>
|     |     |     <title>some_text</title>
|     |     |     <link>some_link</title>
|     |     </image>
|     |     <item>
|     |     |     <title>some_text</title>
|     |     |     <link>some_link</title>
|     |     </item>
|     |     <item>
|     |     |     <title>some_text</title>
|     |     |     <link>some_link</title>
|     |     </item>
|     </channel>
</rss>
```

I am trying to get the text in the item.link field and I am using the command -
 `console.log("Item Link "+res.rss.channel.item.link.text());`
This doesnt work. Astonishingly if I do-
 `console.log("Item Link "+res.rss.channel.image.link.text());`
it works pretty well. I have tried different Rss feeds but nothing works

**Comment by sahildave** [comment]
Hi this is happening in your example too. In someXml if I access - 
`console.log( res.response.who.location.text() );` to get Belgium, I get the same error  

```
Input: {}
  Failed with: TypeError: Cannot call method 'text' of undefined
    at main.js:100:44
    at Object.saxparser.onend (xmlreader.js:104:10)
    at emit (sax.js:616:33)
    at end (sax.js:655:3)
    at Object.write (sax.js:917:30)
    at Object.SAXParser.close (sax.js:153:38)
    at Object.exports.read (xmlreader.js:157:29)
    at main.js:96:14
```

**Comment by sahildave** [comment]
I think I solved it. I went through your code and sax.js and realised that I would have to use a loop to get the items which have multiple entries, here - <item>. I used:

```
res.rss.channel.item.each(function (i, item){
                console.log("At i=" + i + " Item Title "+ item.title.text());
            });
```
